print("  |\_/|  ")
print(" / @ @ \ ")
print("( > º < )")
print(" `>>x<<´ ")
print(" /  O  \ ")
print("             .--------.")
print("(\_/)       .        .|")
print("(0.0)      .        . |")
print("(> <)     :--------. #|")
print("          | # # # | # |")
print("          | # # # | # |")
print("          | # # # | # |")
print("          | # # # | # |")
print("          | # # # | # |")
print("          | # # # |")
