print("H   H EEEEE L     L      OOO      W   W  OOO  RRRR  L     DDDD  !!")
print("H   H E     L     L     O   O     W W W O   O R   R L     D  D  !!")
print("HHHHH EEEEE L     L     O   O     W W W O   O RRRR  L     D  D  !!")
print("H   H E     L     L     O   O  ,,  W W  O   O R   R L     D  D")
print("H   H EEEEE LLLLL LLLLL  OOO  ,,   W W   OOO  R   R LLLLL DDDD  !!")
